test17

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,29 +3,96 @@ dist: trusty
 os: linux
 language: minimal
 cache:
-  ccache: true
   directories:
   - depends/built
+  - depends/work
   - depends/sdk-sources
   - $HOME/.ccache
 env:
   global:
-    - MAKEJOBS=-j3
-    - RUN_TESTS=false
-    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-    - CCACHE_SIZE=100M
+    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+    - CCACHE_SIZE=250M
     - CCACHE_TEMPDIR=/tmp/.ccache-temp
     - CCACHE_COMPRESS=1
-    - CCACHE_DIR=$HOME/.ccache
+    - MAKEJOBS="-j2"
     - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - WINEDEBUG=fixme-all
-    - DOCKER_PACKAGES="build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
+    - BASE_PACKAGES="libdb4.8-dev libdb4.8++-dev zlib1g-dev zip git build-essential libtool autotools-dev automake pkg-config bsdmainutils curl libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libevent-dev"
   matrix:
+# ARM32
+    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui" 
+# ARM64
+    - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
+# Win32
+    - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev" CONF="" 
+# Win64
+    - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev" CONF="" 
+# x86_64 Linux
+    - HOST=x86_64-unknown-linux-gnu PACKAGES="" CONF="" 
+# Cross-Mac-10.11
+    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11 CONF="" 
+
+before_install:
+    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+install:
+    - sudo add-apt-repository -y ppa:bitcoin/bitcoin
+    - sudo apt-get update
+    - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES 
+    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+before_script:
+    - unset CC; unset CXX
+    - cd $TRAVIS_BUILD_DIR
+    - mkdir -p depends/SDKs depends/sdk-sources
+    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+script:
+
+    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+    - ./autogen.sh
+    - cd depends && make $MAKEJOBS $OPT
+    - cd $TRAVIS_BUILD_DIR && ./configure --prefix=$TRAVIS_BUILD_DIR/depends/$HOST $CONF --disable-tests --disable-hardening --disable-bench
+    - make $MAKEJOBS
+before_deploy:
+    - ./pre-deploy.sh
+deploy:
+  provider: releases
+  api_key: 
+    secure: Yai5OGSMOwPEbA41/N0nZHDx9z6kkIcmYmjo/6qEFVr7GL7VHSvSK7LFcNrUjseSHzLcwVVKRZqL5Dq+VHZsUSOI1IM0t5IXbBCgNyJE23RcxjUZufBPrxjabxrkDhUjSrqBilAFUg2KYFRMDBTGPcdqegpl6wsCIzrNn/wCUOXsib531enc/eMFS+OcZVvihFubX1agI8fq7mdhGuCiRtl73u9wfAxn0ygccgGYhGMqIInHm6B5IrbSRQLl5o599+OTvwf1Zm49ChPsYcvGxvxTlEqooQlHhKn+QNmLFua+u6Ru43bynr+5wMkkVNtW0i+ecl8ypEmkYtEcKF+gDbv3F7Lvj7LtrcBAYM2APrxaYudvOLHV83tJmOdimlxKJUokAtzb+Cs9sddqpkrFRVD/BOxiE0Nj+X1YbBWpN86Xw4fpVWQpRns8ToxHMMpjR2lokBBIyRGCTUTj6WT3fYBcM0dIsZZgPG6MRXHfLVDpYcCujVYs3dLmtoxzqYSWP6QC75D7vxXethEOPawIULHQcGGAR6WHIwaWMo2gOMw1IBt3RqnXDFN/1sd0sugC0+gjUOCCINCxBGzLvbsm1GAy9viGSfi7VPy3LMfI1NGGXI15TTmGmlAomSs9mUG+4hHJmxDZvEvaNKJcDYuK1TU85AXNsmg6xV5Ra9Ugn+Q=
+  file_glob: true
+  file: out/**/zip/*
+  skip_cleanup: true
+  on:
+tags: true
+
+#sudo: required
+#dist: trusty
+#os: linux
+#language: minimal
+#cache:
+#  ccache: true
+#  directories:
+#  - depends/built
+#  - depends/sdk-sources
+#  - $HOME/.ccache
+#env:
+#  global:
+#    - MAKEJOBS=-j3
+#    - RUN_TESTS=false
+#    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
+#    - CCACHE_SIZE=100M
+#    - CCACHE_TEMPDIR=/tmp/.ccache-temp
+#    - CCACHE_COMPRESS=1
+#    - CCACHE_DIR=$HOME/.ccache
+#    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+#    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+#    - WINEDEBUG=fixme-all
+#    - DOCKER_PACKAGES="build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
+#    - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake pkg-config bsdmainutils curl libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libevent-dev libboost-all-dev "
+#matrix:
+ # matrix:
 # ARM
     # - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" GOAL="install" BITCORE_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
 # ARM64 Lukas
-     - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" DEP_OPTS="NO_QT=1" BITCORE_CONFIG="--without-gui"
+  #   - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" DEP_OPTS="NO_QT=1" BITCORE_CONFIG="--without-gui"
 # Win32
     # - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-i686 wine-binfmt wine32" RUN_TESTS=false GOAL="install" BITCORE_CONFIG="--enable-reduce-exports"
 # Win64
@@ -43,67 +110,68 @@ env:
 # Cross-Mac
     #- HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev python3-setuptools-git" BITCORE_CONFIG="--enable-gui --enable-reduce-exports --enable-werror" OSX_SDK=10.11 GOAL="all deploy"
 
-before_install:
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
-    - sudo apt-get install build-essential libboost-all-dev libssl-dev
-install:
-    - env | grep -E '^(CCACHE_|WINEDEBUG|BOOST_TEST_RANDOM|CONFIG_SHELL)' | tee /tmp/env
-    - if [[ $HOST = *-mingw32 ]]; then DOCKER_ADMIN="--cap-add SYS_ADMIN"; fi
-    - DOCKER_ID=$(docker run $DOCKER_ADMIN -idt --mount type=bind,src=$TRAVIS_BUILD_DIR,dst=$TRAVIS_BUILD_DIR --mount type=bind,src=$CCACHE_DIR,dst=$CCACHE_DIR -w $TRAVIS_BUILD_DIR --env-file /tmp/env ubuntu:18.04)
-    - DOCKER_EXEC () { docker exec $DOCKER_ID bash -c "cd $PWD && $*"; }
-    - if [ -n "$DPKG_ADD_ARCH" ]; then DOCKER_EXEC dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-    - travis_retry DOCKER_EXEC apt-get update
-    - travis_retry DOCKER_EXEC apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES $DOCKER_PACKAGES
+#before_install:
+ #   - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+  #  - sudo apt-get install build-essential libboost-all-dev libssl-dev
+#install:
+ #   - env | grep -E '^(CCACHE_|WINEDEBUG|BOOST_TEST_RANDOM|CONFIG_SHELL)' | tee /tmp/env
+  #  - if [[ $HOST = *-mingw32 ]]; then DOCKER_ADMIN="--cap-add SYS_ADMIN"; fi
+   # - DOCKER_ID=$(docker run $DOCKER_ADMIN -idt --mount type=bind,src=$TRAVIS_BUILD_DIR,dst=$TRAVIS_BUILD_DIR --mount type=bind,src=$CCACHE_DIR,dst=$CCACHE_DIR -w $TRAVIS_BUILD_DIR --env-file /tmp/env ubuntu:18.04)
+    #- DOCKER_EXEC () { docker exec $DOCKER_ID bash -c "cd $PWD && $*"; }
+    #- if [ -n "$DPKG_ADD_ARCH" ]; then DOCKER_EXEC dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
+    #- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
+    #- travis_retry DOCKER_EXEC apt-get update
+    #- travis_retry DOCKER_EXEC apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES $DOCKER_PACKAGES
     # libdb4.8-dev libdb4.8++-dev
-before_script:
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [[ $HOST = *-mingw32 ]]; then DOCKER_EXEC update-alternatives --set $HOST-g++ \$\(which $HOST-g++-posix\); fi
-    - if [ -z "$NO_DEPENDS" ]; then DOCKER_EXEC CONFIG_SHELL= make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS; fi
-script:
-    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - BITCORE_CONFIG_ALL="--disable-dependency-tracking --disable-hardening --disable-tests --disable-bench --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-    - if [ -z "$NO_DEPENDS" ]; then DOCKER_EXEC ccache --max-size=$CCACHE_SIZE; fi
-    - test -n "$CONFIG_SHELL" && DOCKER_EXEC "$CONFIG_SHELL" -c "./autogen.sh" || DOCKER_EXEC ./autogen.sh
-    - mkdir build && cd build
-    - DOCKER_EXEC ../configure --cache-file=config.cache $BITCORE_CONFIG_ALL $BITCORE_CONFIG || ( cat config.log && false)
-    - DOCKER_EXEC make distdir VERSION=$HOST
-    - cd bitcoin-$HOST
-    - DOCKER_EXEC ./configure --cache-file=../config.cache $BITCORE_CONFIG_ALL $BITCORE_CONFIG || ( cat config.log && false)
-    - DOCKER_EXEC make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && DOCKER_EXEC make $GOAL V=1 ; false )
-    - if [ "$RUN_TESTS" = "true" ]; then DOCKER_EXEC LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib make $MAKEJOBS check VERBOSE=1; fi
-    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude feature_pruning,feature_dbcrash"; fi
-    - if [ "$RUN_TESTS" = "true" ]; then DOCKER_EXEC test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet --failfast ${extended}; fi
-after_script:
-    - echo $TRAVIS_COMMIT_RANGE
-    - echo $TRAVIS_COMMIT_LOG
+#before_script:
+#    - mkdir -p depends/SDKs depends/sdk-sources
+ #   - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+  #  - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+  #  - if [[ $HOST = *-mingw32 ]]; then DOCKER_EXEC update-alternatives --set $HOST-g++ \$\(which $HOST-g++-posix\); fi
+   # - if [ -z "$NO_DEPENDS" ]; then DOCKER_EXEC CONFIG_SHELL= make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS; fi
+#script:
+ #   - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
+  #  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+   # - BITCORE_CONFIG_ALL="--disable-dependency-tracking --disable-hardening --disable-tests --disable-bench --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+    #- if [ -z "$NO_DEPENDS" ]; then DOCKER_EXEC ccache --max-size=$CCACHE_SIZE; fi
+   # - test -n "$CONFIG_SHELL" && DOCKER_EXEC "$CONFIG_SHELL" -c "./autogen.sh" || DOCKER_EXEC ./autogen.sh
+    #- mkdir build && cd build
+    #- DOCKER_EXEC ../configure --cache-file=config.cache $BITCORE_CONFIG_ALL $BITCORE_CONFIG || ( cat config.log && false)
+    #- DOCKER_EXEC make distdir VERSION=$HOST
+    #- cd bitcoin-$HOST
+    #- DOCKER_EXEC ./configure --cache-file=../config.cache $BITCORE_CONFIG_ALL $BITCORE_CONFIG || ( cat config.log && false)
+    #- DOCKER_EXEC make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && DOCKER_EXEC make $GOAL V=1 ; false )
+    #- if [ "$RUN_TESTS" = "true" ]; then DOCKER_EXEC LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib make $MAKEJOBS check VERBOSE=1; fi
+    #- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude feature_pruning,feature_dbcrash"; fi
+    #- if [ "$RUN_TESTS" = "true" ]; then DOCKER_EXEC test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet --failfast ${extended}; fi
+#after_script:
+ #   - echo $TRAVIS_COMMIT_RANGE
+  #  - echo $TRAVIS_COMMIT_LOG
 
-jobs:
-  include:
-    - stage: lint
-      sudo: false
-      cache: false
-      addons:
-        apt:
-          packages:
-            - python3-pip
-            - shellcheck
-      install:
-        - travis_retry pip3 install flake8 --user
-      before_script:
-        - git fetch --unshallow
-      script:
-        - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then test/lint/commit-script-check.sh $TRAVIS_COMMIT_RANGE; fi
-        - test/lint/git-subtree-check.sh src/crypto/ctaes
-        - test/lint/git-subtree-check.sh src/secp256k1
-        - test/lint/git-subtree-check.sh src/univalue
-        - test/lint/git-subtree-check.sh src/leveldb
-        - test/lint/check-doc.py
-        - test/lint/check-rpc-mappings.py .
-        - test/lint/lint-all.sh
-        - if [ "$TRAVIS_REPO_SLUG" = "bitcoin/bitcoin" -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then
-              while read LINE; do travis_retry gpg --keyserver hkp://subset.pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys &&
-              travis_wait 50 contrib/verify-commits/verify-commits.py;
-          fi
+#jobs:
+ # include:
+  #  - stage: lint
+   #   sudo: false
+    #  cache: false
+     # addons:
+      #  apt:
+       #   packages:
+        #    - python3-pip
+         #   - shellcheck
+      #install:
+       # - travis_retry pip3 install flake8 --user
+      #before_script:
+      #  - git fetch --unshallow
+      #script:
+      #  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then test/lint/commit-script-check.sh $TRAVIS_COMMIT_RANGE; fi
+      #  - test/lint/git-subtree-check.sh src/crypto/ctaes
+      #  - test/lint/git-subtree-check.sh src/secp256k1
+      #  - test/lint/git-subtree-check.sh src/univalue
+      #  - test/lint/git-subtree-check.sh src/leveldb
+      #  - test/lint/check-doc.py
+      #  - test/lint/check-rpc-mappings.py .
+      #  - test/lint/lint-all.sh
+      #  - if [ "$TRAVIS_REPO_SLUG" = "bitcoin/bitcoin" -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then
+      #        while read LINE; do travis_retry gpg --keyserver hkp://subset.pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys &&
+      #        travis_wait 50 contrib/verify-commits/verify-commits.py;
+      #    fi
